# Generated by Django 4.2 on 2023-04-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="stdSEX", new_name="stdSex",
        ),
    ]
